### ISSUE TITLE
Allow reusing access tokens when creating OmhAuthClient instance

### ISSUE THREAD

**Issue by TranceLove** [openmobilehub/android-omh-auth#107]
**Checklist**

- [x] I've checked the feature request list and there's no request created for this purpose
- [x] I've tried discussing this first in the discussion section to find out if there's something similar implemented (Or checked it by myself)

**Is your feature request related to a problem? Please describe.**
With current API, it seems impossible to reuse the provider's access token across app sessions. This makes users need to login to the provider every time the app needs to call the service provider's APIs.

**Describe the solution you'd like**
It should be possible to specify an existing access token when constructing the auth client, so user doesn't need to login to the service provider every time. Underneath `android-omh-auth` can still call service provider to verify the access token, or request refresh if the token had been expired.

No need for `android-omh-auth` to consider where and how the access token is stored, although it is a nice-to-have.

**Describe alternatives you've considered**
N/A

**Comment by dzuluaga** [comment]
@Nataliagros and @adamTrz PTAL. High priority.

CC - @prestonlau @itsme291

**Comment by maciekBudzinski** [comment]
Hi @TranceLove
As far as I understand the issue, your goal is to be able to reuse the token between app sessions.
In the current `android-omh-auth` implementation it's supported:
- via  `GoogleSignIn.getLastSignedInAccount` method for [Google GMS Plugin](https://github.com/openmobilehub/android-omh-auth/blob/e3cecfffc694385ef12dd5d1d565ed4c2415daac/packages/plugin-google-gms/src/main/java/com/openmobilehub/android/auth/plugin/google/gms/GmsCredentials.kt#L20)
- via `AccessToken.getCurrentAccessToken` method for [Facebook](https://github.com/openmobilehub/android-omh-auth/blob/e3cecfffc694385ef12dd5d1d565ed4c2415daac/packages/plugin-facebook/src/main/java/com/openmobilehub/android/auth/plugin/facebook/FacebookCredentials.kt#L17)
- via `EncryptedSharedPreferences` for all other providers: [Google Non-GMS](https://github.com/openmobilehub/android-omh-auth/blob/e3cecfffc694385ef12dd5d1d565ed4c2415daac/packages/plugin-google-non-gms/src/main/java/com/openmobilehub/android/auth/plugin/google/nongms/data/login/AuthRepositoryImpl.kt#L120), [Dropbox](https://github.com/openmobilehub/android-omh-auth/blob/e3cecfffc694385ef12dd5d1d565ed4c2415daac/packages/plugin-dropbox/src/main/java/com/openmobilehub/android/auth/plugin/dropbox/DropboxRepository.kt#L41) and [Microsoft](https://github.com/openmobilehub/android-omh-auth/blob/e3cecfffc694385ef12dd5d1d565ed4c2415daac/packages/plugin-microsoft/src/main/java/com/openmobilehub/android/auth/plugin/microsoft/MicrosoftRepository.kt#L23)

Below you can find two demos from Google-GMS and Dropbox that presents that access tokens stay the same between app launches:

https://github.com/user-attachments/assets/371ad630-7e3e-4162-9bcf-8743330db3fe

https://github.com/user-attachments/assets/af702d20-95fe-4c4a-9694-df01b31dead4

Additionally, I encourage to check out the sample app.

**Comment by adamTrz** [comment]
@TranceLove - I will close this issue but please feel free to reopen if the issue persists :)

**Comment by dzuluaga** [comment]
Confirmed by @TranceLove. They managed to integrate it. Thanks @maciekBudzinski for the promptly answer.
