### ISSUE TITLE
Request to Enable Edge-to-Edge Support

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/android-omh-auth#61]
Hello Natalia and Andrei,

I've noticed the sample app doesn't utilize edge-to-edge layout, which enhances user experience by extending the UI to cover the entire screen, including the status and navigation bar areas. This is a recommended practice for modern Android apps, and according to the [Android Developers Guide](https://developer.android.com/develop/ui/views/layout/edge-to-edge), it's straightforward to implement.

Enabling edge-to-edge could significantly improve the app's aesthetic and functionality. Could this feature be considered for an upcoming update?

Thank you for your work on this project!

**Comment by DamianNowak5f** [comment]
Hi, edge-to-edge support was already introduced as a part of [this issue](https://github.com/openmobilehub/android-omh-auth/issues/55). I am closing this one as it seems duplicated, but if you expect something different then please let us know. Cheers!

**Comment by dzuluaga** [comment]
My bad. Looks good. Thanks!
