### ISSUE TITLE
Cryptic error due to missing variables; consider using Secrets Gradle Plugin

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/android-omh-auth#7]
Currently, I'm encountering a confusing error when building the project:

```
Build file '/xxx/tools/git/android-omh-auth/apps/auth-sample/build.gradle.kts' line: 68

* What went wrong:
null cannot be cast to non-null type kotlin.String
```

It seems this error stems from missing variables that are not clearly indicated as being required by the build process.  This can lead to developer confusion and wasted time figuring out the problem.

**Proposed Improvement**

Could we explore using a solution like Google's Secrets Gradle Plugin ([https://github.com/google/secrets-gradle-plugin](https://github.com/google/secrets-gradle-plugin)) to manage these variables? This approach is similar to how OMH 1.0 reads variables from `local.properties`, and has several advantages:

* **Enhanced Security:** It keeps sensitive variables out of version control.
* **Improved Developer Experience:** It gives clearer guidance when required variables are missing, preventing cryptic errors.

**Question**

Are there reasons why using the Secrets Gradle Plugin (or a similar solution) might not be suitable for this project? If not, it could be a worthwhile upgrade in terms of security and developer experience.

Let me know if you think it's a good fit!

Also, would it be possible to get consensus on which method to read local.properties across all modules?

**Comment by adamTrz** [comment]
I'm closing this issue in favour of #31
