### ISSUE TITLE
Missing `local.properties` file

### ISSUE THREAD

**Issue by VishnuSanal** [openmobilehub/android-omh-auth#73]
the function `#setupSecrets` on `build.gradle.kts (:app)` requires the `local.properties` file to complete sync. I have commented the code out `(build.gradle.kts (:app) L#73)` to try & build the project. this did the trick to successfully compile, but we wasn't able to build since the strings were not exported, resulting an error being shown at `AndroidManifest L#46`.

is it that the `local.properties` wasn't added to git because of gitignore, or is it that I am supposed to create the file with my own API keys? if it is the latter, this should be specified in the documentation.

I have tried both the `code-starter` branch and the `main` branch.

also, the current behavior throws weird Gradle dependency errors when the file is missing. verifying that the file exists & throwing errors likewise helps! attaching sample code below. :)

```
if (file(rootDir.path.plus("local.properties")).exists())
            setupSecrets(this)
        else
            throw GradleException("Missing local.properties file")
```

PS: I'd happily make a PR for the change if you will. :)

edit: @Nataliagros ping

**Comment by ddolny** [comment]
Hello @VishnuSanal , thank you for reporting this issue, we were aware of it, and we are working on the solution. It should be ready soon.

**Comment by VishnuSanal** [comment]
Hi @ddolny, any updates on this? Also, shall I create the aforementioned PR?

**Comment by ddolny** [comment]
Hi, I've created update with the fix. check for the existence of local.properties would not work, as it's created by default by IDE. But Right now error returned by the gradle is more informative.
