### ISSUE TITLE
broken links on README & documentation page

### ISSUE THREAD

**Issue by VishnuSanal** [openmobilehub/android-omh-auth#79]
the text "Google GMS and non-GMS" points [here](https://www.openmobilehub.com/android-omh-auth/advanced-docs/advanced-docs/plugin-google-gms/README), which gives a 404. this should actually point [here](https://www.openmobilehub.com/android-omh-auth/advanced-docs/plugin-google-gms/README/).

likewise is the case with the link [here](https://www.openmobilehub.com/android-omh-auth/advanced-docs/plugin-google-non-gms/README/)

**Comment by dzuluaga** [comment]
Dupped issue. Docs updated. See #84
