### ISSUE TITLE
Publish on Maven/Jitpack

### ISSUE THREAD

**Issue by VishnuSanal** [openmobilehub/android-omh-auth#83]
publishing on popular repositories makes it much easier to integrate OMH SDKs to existing applications. or, please correct me is there is a specific reason this is not done in the first place?

for eg: [Spotless on Maven](https://mvnrepository.com/artifact/com.diffplug.spotless/spotless-maven-plugin/2.43.0) / [Retrofit on Jitpack](https://jitpack.io/p/square/retrofit).

**Comment by dzuluaga** [comment]
The link in #84 should provide this context with `implementation` along with the coordinates to reference the artifacts from Maven central.

**Comment by dzuluaga** [comment]
Closing this issue. Feel free to reply if it wasn't addressed.

**Comment by dzuluaga** [comment]
Hey @VishnuSanal to elaborate on my previous response. I was able to include the dependencies with no issues. Let me know if you're still facing the same issue.

```
    implementation("com.openmobilehub.android.auth:plugin-google-gms:2.0.0")
    implementation("com.openmobilehub.android.auth:plugin-google-non-gms:2.0.0")
```
