### ISSUE TITLE
How to integrate to another application?

### ISSUE THREAD

**Issue by VishnuSanal** [openmobilehub/android-omh-auth#84]
The current docs guides to integrate the SDK into a starter application. But, how to integrate it into an existing application, say Amaze? 

http://openmobilehub.org/android-omh-auth/advanced-docs/advanced-docs/plugin-google-gms/README documentation links like this gives me a 404 too?

Usually, we'll have seamless integration by adding one dependency. (#83 was a suggestion for this) We'll be good to go after that. But, in the case on OMH, I didn't find such a way.

I even tried building the plugin into a JAR & running it as a local dependency; I'm unable to make it work either.

Please take a look, or correct me if I'm missing something. :)

**Comment by dzuluaga** [comment]
Hi Vishnu,

Thanks for reaching out. The documentation has been updated to GitHub.io pages temporarily. The links in this section should be up to date. Please give it a try and let us know if you encounter any issues: [Documentation](https://github.com/openmobilehub/android-omh-auth#documentation).

If you face any issues or need further assistance, please let us know. Additionally, if you find any documentation pointing to openmobilehub.com, feel free to raise a bug.

**Comment by dzuluaga** [comment]
@VishnuSanal are you still running into this issue?

**Comment by VishnuSanal** [comment]
hi diego, I am afraid not.

I tried the steps mentioned [here](https://openmobilehub.github.io/android-omh-auth/advanced-docs/core/advanced/OMH-Core/). it gave me an error:

```Plugin [id: 'com.openmobilehub.android.core'] was not found in any of the following sources:```

then links led me [here](https://github.com/openmobilehub/android-omh-core) to the video, which was publishing the library to maven local. hence, I did `./gradlew publishToMavenLocal` on cloned repo, but that failed with an error.

I also tried the steps mentioned [here](https://openmobilehub.github.io/android-omh-auth/advanced-docs/core/advanced/OMH-Auth-Client/), but for the version I had to search up the plugin ID which led to [this](https://mvnrepository.com/artifact/com.openmobilehub.android/omh-core/2.0.0) page. this got built, but I couldn't override the interfaces.

**Comment by dzuluaga** [comment]
Thanks, @VishnuSanal. I was able to reproduce this issue in a clean Android project, indicating that there might be something missing in how the module was published to Maven Central. I even tried hardcoding the version as shown below, but I keep encountering the same error.

```kotlin
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("com.openmobilehub.android.omh-core") version "2.0.1-beta"
}
```

@Nataliagros @artus9033 - could you please look into this?

CC: @itsme291 @prestonlau

**Comment by VishnuSanal** [comment]
update: thanks Diego, I was able to add the dependencies as mentioned [here](https://github.com/openmobilehub/android-omh-auth/issues/83#issuecomment-2168566219)! now, I am getting a `DEVELOPER_ERROR`, I am figuring out a fix for it.

**Comment by maciekBudzinski** [comment]
@VishnuSanal Please let us know if you were able to resolve the `DEVELOPER_ERROR`. Below, I'm listing potential solutions:
- Make sure you call the `initialize` method first (especially important if you work with Microsoft): https://github.com/openmobilehub/android-omh-auth?tab=readme-ov-file#initialize-client
- If you do not use omh-core gradle plugin make sure that you pass the correct paths for the `gms` and `nongms`. Here's an example from sample application: https://github.com/openmobilehub/android-omh-auth/blob/main/apps/auth-sample/src/main/java/com/openmobilehub/android/auth/sample/di/SingletonModule.kt#L37

**Comment by dzuluaga** [comment]
I've also experienced this error if the SHA* signature in GCP doesn't match with my keystore. This article isn't specific for OMH but in general for apps registering and matching their SHA. https://medium.com/@andres230687/error-developer-error-signing-google-login-react-native-d67d9217ce8

**Comment by VishnuSanal** [comment]
hi, thanks Diego, Maciej! I can now integrate the Auth SDK in our application. :)

btw, I can write a step by step blog/guide on the steps to be followed to do the implementation, if you'd let me. :D I had to do a lot of _figuring out_ to get started!

**Comment by dzuluaga** [comment]
Thanks, Vishnu. I appreciate your persistence in making this happen. Our goal is to make the developer experience as smooth as possible. Could you please raise these devx issues as GitHub bugs? Also, we would love to see a draft of the blog post.

CC - @itsme291 @prestonlau
