### ISSUE TITLE
Broken link error 404 at https://openmobilehub.github.io/android-omh-auth/advanced-docs/plugin-google-non-gms/README/

### ISSUE THREAD

**Issue by hwag2024** [openmobilehub/android-omh-auth#91]
**Checklist**

- [ ] I've checked the issues list and there's no issue created for this behavior
- [x] I'm not asking for help in this section. _Use our discussions section for that_

**Describe the bug**

**It returns a 404 
https://openmobilehub.github.io/android-omh-auth/advanced-docs/plugin-google-non-gms/README

**To Reproduce**
1. Go to '[...](https://openmobilehub.github.io/android-omh-auth/advanced-docs/plugin-google-non-gms/README/)'
2. Click on 'Here'
4. See error： 404

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dzuluaga** [comment]
Hi @Nataliagros it looks like the url in the markdown is missing something. Can someone from the team look into it? Thanks!

**Comment by dzuluaga** [comment]
One suggestion. See this comment https://github.com/openmobilehub/android-omh-auth/pull/94#issuecomment-2278850317

**Comment by dzuluaga** [comment]
@hwag2024 This one should be working. PTAL
